title: Black Diamond field mapping
order: 20
backends:
  - bdiamond
logsources:
  windows:
    product: windows
    conditions:
      taxevtst: 1
  windows-powershell:
    product: windows
    service: powershell
    conditions:
      trgdtname: MATCH REGEX ("(?i)(powershell|cmd)(.exe)")
      vec: 4104
logsourcemerging: or