outputCSV: false
general:
  additionalWhereClause: tenantname NOT IN "tenantnameProvisioning"
  fulltextSearchField: einfo
  sevMapping: 
    informational: 24h
    low: 18h
    medium: 12h
    high: 6h
    critical: 3h
  sevMappingAsNum: 
    unclassified: 0
    informational: 1
    low: 2
    medium: 3
    high: 4
    critical: 5
  havingClauseFields:
    - tenantname
    - obsname
    - obsip
others:
  product:
      windows: taxevtst=1
      linux: taxevtst=1
  service:
    powershell: ( trgdtname MATCH REGEX ("(?i)(powershell|cmd)(.exe)?") OR vec=4104)
    auditd: trgsvcname='audit'