outputCSV: false
general:
  additionalWhereClause: tenantname not in "tenantnameProvisioning"
  fulltextSearchField: einfo
  sevMapping: 
    informational: 24h
    low: 18h
    medium: 12h
    high: 6h
    critical: 3h
  sevMappingAsNum: 
    unclassified: 0
    informational: 1
    low: 2
    medium: 3
    high: 4
    critical: 5
  havingClauseFields:
    - tenantname
    - obsname
    - obsip
ignoredFields:
  - DestinationIsIpv6
  - Device
  - Path
  - EngineVersion
  - HostVersion
  - Initiated
  - ObjectClass
  - ParentIntegrityLevel
  - Source
  - Signed
  - service
  - sha1
multiMappingFields:
  Destination:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  Details:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  FileName:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  HiveName:
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  Image:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  ImageLoaded:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  ParentCommandLine:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  ParentImage:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  ProcessName:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  TargetImage:
    trgdtnamespace: '(\w):\\'
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
  TargetObject:
    trgdtcontainer: '\*?(\\[^\s|\.]+)\\\*?'
    trgdtname: '[^\\|\s]+\.\S+$'
others:
  product:
      windows: taxevtst=1
      linux: taxevtst=1
  service:
    powershell: ( trgdtname match regex ("(?i)(powershell|cmd)(.exe)?") or vec=4104)
    auditd: trgsvcname='audit'